// Code generated by "stringer -type=NodeType"; DO NOT EDIT.

package xtree

import "strconv"

const _NodeType_name = "NotXMLDirectoryDocumentElementAttributeDataCDataCommentDeclarationDoctypeProcInstr"

var _NodeType_index = [...]uint8{0, 6, 15, 23, 30, 39, 43, 48, 55, 66, 73, 82}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
